"""Kimi-K3 MoE layer assembled from unchanged TRT-LLM modules.

Wiring follows TRT-LLM's ``Deepseekv3MoE``
(``tensorrt_llm/_torch/models/modeling_deepseekv3.py`` in the ``trt-k3-prod``
container, TRT-LLM 1.3.0rc19 fork): shared experts are one ``GatedMLP``
(2 shared experts x 3072 = intermediate 6144) built with ``reduce_output=False``
plus an external ``AllReduce``; routed experts are a ``ConfigurableMoE``
(TRTLLMGenFusedMoE + NVLinkOneSided A2A) built through the unchanged
``bench_moe`` harness by the caller. Every kernel is an unchanged
``torch.ops.trtllm`` compiled op or TRT-LLM Python module; this file only
composes them.

Two modes on the same GPU count N:

- ``tp`` (finalized TRT-LLM TP reference for the shared path): every rank
  holds the full global token set; shared experts are TP-sharded
  (intermediate 6144/N per rank) and their partial output is TP-allreduced
  over [T, hidden], exactly as ``Deepseekv3MoE`` does when attention DP is
  off. The routed path is EP with NVLinkOneSided A2A on this rank's token
  slice (per task spec; see README for the deviation note vs pure TEP).
- ``cp`` (emulation): every rank owns 1/N of the tokens; shared experts are
  computed locally with FULL replicated weights (no TP collective on the
  shared path); the routed path is the identical EP A2A on the same local
  tokens. This mirrors what TRT-LLM itself does when attention DP is on
  (``_compute_shared_expert_tp_size`` returns ``shared_tp_size=1``).
"""

from __future__ import annotations

from typing import Optional

import torch
from torch import nn

HIDDEN_SIZE = 7168
NUM_SHARED_EXPERTS = 2
MOE_INTERMEDIATE = 3072
SHARED_INTERMEDIATE = NUM_SHARED_EXPERTS * MOE_INTERMEDIATE  # 6144
MXFP4_GROUP = 32


def make_shared_expert_checkpoint_weights(
    hidden_size: int,
    intermediate_size: int,
    device: torch.device,
) -> dict[str, dict[str, torch.Tensor]]:
    """Deterministic W4A8_MXFP4_MXFP8 checkpoint-format shared-expert weights.

    Generated by the IMPORTED, unchanged ``MXFP4MXFP8QuantizeUtil.create_weights``
    (tests/unittest ``_torch/modules/moe/quantize_utils.py``) with
    ``num_experts=1`` — the same generator (and internal seed 42) that produces
    the routed-expert test weights. Both dims are already multiples of the
    TRTLLM alignments (128 / 512), so no padding occurs and the returned dicts
    load directly into TRT-LLM ``Linear`` (``weight`` + ``weight_scale``) at
    any TP size.
    """
    from _torch.modules.moe.quantize_utils import MXFP4MXFP8QuantizeUtil

    from tensorrt_llm.models.modeling_utils import QuantAlgo, QuantConfig

    assert hidden_size % MXFP4_GROUP == 0 and intermediate_size % MXFP4_GROUP == 0
    with torch.cuda.device(device):
        util = MXFP4MXFP8QuantizeUtil(
            num_experts=1,
            dtype=torch.bfloat16,
            intermediate_size=intermediate_size,
            hidden_size=hidden_size,
            quant_config=QuantConfig(quant_algo=QuantAlgo.W4A8_MXFP4_MXFP8),
        )
        weights = util.create_weights(weight_alignment=128, input_hidden_alignment=512)
    return {
        name: {
            "weight": weights[f"0.{name}.weight"].to(device),
            "weight_scale": weights[f"0.{name}.weight_scale"].to(device),
        }
        for name in ("w1", "w2", "w3")
    }


class KimiK3SharedExperts(nn.Module):
    """Shared experts as one TRT-LLM ``GatedMLP`` (+ ``AllReduce`` in TP mode).

    ``mode='tp'``: ``overridden_tp_size=world_size`` (intermediate sharded),
    external allreduce over the full token set — Deepseekv3MoE TP wiring.
    ``mode='cp'``: ``overridden_tp_size=1`` (full replicated weights), no
    collective — Deepseekv3MoE attention-DP wiring.
    """

    def __init__(
        self,
        *,
        mode: str,
        world_size: int,
        rank: int,
        device: torch.device,
        hidden_size: int = HIDDEN_SIZE,
        intermediate_size: int = SHARED_INTERMEDIATE,
        dtype: torch.dtype = torch.bfloat16,
    ) -> None:
        super().__init__()
        if mode not in ("tp", "cp"):
            raise ValueError(f"mode must be 'tp' or 'cp', got {mode!r}")
        from transformers.configuration_utils import PretrainedConfig

        from tensorrt_llm._torch.distributed import AllReduce
        from tensorrt_llm._torch.model_config import ModelConfig
        from tensorrt_llm._torch.modules.gated_mlp import GatedMLP
        from tensorrt_llm.mapping import Mapping
        from tensorrt_llm.models.modeling_utils import QuantAlgo, QuantConfig

        self.mode = mode
        self.world_size = world_size
        self.hidden_size = hidden_size
        self.intermediate_size = intermediate_size

        mapping = Mapping(world_size=world_size, tp_size=world_size, enable_attention_dp=False)
        mapping.rank = rank
        pretrained_config = PretrainedConfig()
        pretrained_config.hidden_size = hidden_size
        pretrained_config.intermediate_size = intermediate_size
        pretrained_config.torch_dtype = dtype
        model_config = ModelConfig(
            pretrained_config=pretrained_config,
            mapping=mapping,
            quant_config=QuantConfig(quant_algo=QuantAlgo.W4A8_MXFP4_MXFP8),
        )

        shared_tp_size = world_size if mode == "tp" else 1
        self.mlp = GatedMLP(
            hidden_size=hidden_size,
            intermediate_size=intermediate_size,
            bias=False,
            dtype=dtype,
            config=model_config,
            overridden_tp_size=shared_tp_size,
            reduce_output=False,
            is_shared_expert=True,
        )
        checkpoint = make_shared_expert_checkpoint_weights(
            hidden_size, intermediate_size, device
        )
        self.mlp.gate_up_proj.load_weights([checkpoint["w1"], checkpoint["w3"]])
        self.mlp.down_proj.load_weights([checkpoint["w2"]])
        self.mlp.cuda(device)

        self.allreduce = None
        if mode == "tp" and world_size > 1:
            self.allreduce = AllReduce(mapping=mapping)

    def weight_bytes(self) -> int:
        total = 0
        for tensor in list(self.mlp.parameters()) + list(self.mlp.buffers()):
            total += tensor.numel() * tensor.element_size()
        return total

    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:
        return self.mlp(hidden_states)


class KimiK3MoELayerBaseline(nn.Module):
    """Shared experts + 896 routed experts (top-16), TP or CP token layout.

    ``routed_moe`` is an unchanged TRT-LLM ``ConfigurableMoE`` built by the
    caller through the unchanged ``bench_moe`` harness (TRTLLMGenFusedMoE +
    NVLinkOneSided). The router gate GEMM is intentionally outside this
    module: benchmarks inject balanced projected router logits (identical in
    both modes), following the prior MegaMoE receipts.
    """

    def __init__(
        self,
        *,
        mode: str,
        routed_moe: nn.Module,
        shared_experts: KimiK3SharedExperts,
        rank: int,
    ) -> None:
        super().__init__()
        assert shared_experts.mode == mode
        self.mode = mode
        self.rank = rank
        self.routed_moe = routed_moe
        self.shared_experts = shared_experts

    # Separate methods so the benchmark can wrap each phase with CUDA events.
    def shared_forward(self, hidden_states: torch.Tensor) -> torch.Tensor:
        return self.shared_experts(hidden_states)

    def allreduce_forward(self, partial: torch.Tensor) -> torch.Tensor:
        return self.shared_experts.allreduce(partial)

    def routed_forward(
        self,
        hidden_local: torch.Tensor,
        router_logits_local: torch.Tensor,
        all_rank_num_tokens: list[int],
    ) -> torch.Tensor:
        return self.routed_moe.forward(
            hidden_local,
            router_logits_local,
            all_rank_num_tokens=all_rank_num_tokens,
        )

    def forward(
        self,
        hidden_local: torch.Tensor,
        router_logits_local: torch.Tensor,
        all_rank_num_tokens: list[int],
        hidden_full: Optional[torch.Tensor] = None,
    ) -> torch.Tensor:
        """Return this rank's [local_tokens, hidden] slice of the layer output."""
        if self.mode == "tp":
            assert hidden_full is not None, "TP mode needs the replicated global tokens"
            shared_partial = self.shared_forward(hidden_full)
            shared_full = self.allreduce_forward(shared_partial)
            offset = sum(all_rank_num_tokens[: self.rank])
            shared_local = shared_full[offset : offset + hidden_local.shape[0]]
        else:
            shared_local = self.shared_forward(hidden_local)
        routed_local = self.routed_forward(
            hidden_local, router_logits_local, all_rank_num_tokens
        )
        return shared_local + routed_local
